version: "3"
services:
   
   front-end:
       container_name: front-end
       build: ./front-end
       image: front-end
        
   nginx-frontend:
     build: ./front-end/nginx 
     image: nginx-frontend
     container_name: nginx-frontend
     ports:
       - 80:80
       - 443:443
     volumes:
       - frontend-app:/app/
       - data:/data/
     depends_on:
       - backend
       - slim
     command: nginx -g 'daemon off';

   backend:
      build: ./backend
      container_name: backend
      image: backend
      environment:
        - APP_NAME=backend
        - ENV=prod
      expose:
        - 81

 
   slim:
     build: ./slim
     hostname: slim
     container_name: slim
     image: slim
     ports:
       - 82:8002
     expose:
       - 8002
     volumes:
       - slim-app:/var/www
       - slim-public:/var/www/html
     command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
     

volumes:
   frontend-app:
      driver: local
      driver_opts:
         o: bind
         type: none
         device: /home/ubuntu/virginia-ecommerce/front-end
   slim-app:
      driver: local
      driver_opts:
         o: bind
         type: none
         device: /home/ubuntu/virginia-ecommerce/slim/app
   slim-public:
      driver: local
      driver_opts:
         o: bind
         type: none
         device: /home/ubuntu/virginia-ecommerce/slim/app/public
   data:
       driver: local
       driver_opts:
          o: bind
          type: none
          device: /home/ubuntu/virginia-ecommerce/data
